remove ril-caf
FAILED: /root/dureo/out/target/product/gemini/obj_arm/SHARED_LIBRARIES/libril_intermediates/ril.o
/bin/bash -c "PWD=/proc/self/cwd /usr/local/bin/ccache prebuilts/clang/host/linux-x86/clang-3859424/bin/clang++ 	-I device/xiaomi/msm8996-common/include -I external/nanopb-c -I hardware/ril-caf/libril/../include -I hardware/ril-caf/libril -I /root/dureo/out/target/product/gemini/obj_arm/SHARED_LIBRARIES/libril_intermediates -I /root/dureo/out/target/product/gemini/gen/SHARED_LIBRARIES/libril_intermediates -I libnativehelper/include/nativehelper \$(cat /root/dureo/out/target/product/gemini/obj_arm/SHARED_LIBRARIES/libril_intermediates/import_includes)  -I system/core/include -I system/media/audio/include -I hardware/libhardware/include -I hardware/libhardware_legacy/include -I hardware/ril/include -I libnativehelper/include -I frameworks/native/include -I frameworks/native/opengl/include -isystem frameworks/av/include -isystem /root/dureo/out/target/product/gemini/obj/include -isystem bionic/libc/arch-arm/include -isystem bionic/libc/include -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/uapi/asm-arm -isystem bionic/libc/kernel/android/uapi -c  -fno-exceptions -Wno-multichar -ffunction-sections -fdata-sections -funwind-tables -fstack-protector-strong -Wa,--noexecstack -Werror=format-security -D_FORTIFY_SOURCE=2 -fno-short-enums -no-canonical-prefixes -DNDEBUG -g -Wstrict-aliasing=2 -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -DNDEBUG -UDEBUG -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-expansion-to-defined -fdebug-prefix-map=\$PWD/= -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=date-time -nostdlibinc -msoft-float -mfloat-abi=softfp -mfpu=neon -mcpu=cortex-a7 -mfpu=neon-fp-armv8 -D__ARM_FEATURE_LPAE=1 -target arm-linux-androideabi -Bprebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin  -Wsign-promo -Wno-inconsistent-missing-override -Wno-null-dereference -fvisibility-inlines-hidden -std=gnu++14 -mthumb -Os -fomit-frame-pointer -fno-strict-aliasing  -fno-rtti -Wno-unused-parameter -fPIC -D_USING_LIBCXX -fsanitize=integer -fsanitize-trap=all -ftrap-function=abort -DANDROID_STRICT   -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=return-type   -MD -MF /root/dureo/out/target/product/gemini/obj_arm/SHARED_LIBRARIES/libril_intermediates/ril.d -o /root/dureo/out/target/product/gemini/obj_arm/SHARED_LIBRARIES/libril_intermediates/ril.o hardware/ril-caf/libril/ril.cpp"
In file included from hardware/ril-caf/libril/ril.cpp:48:
In file included from hardware/ril-caf/libril/RilSapSocket.h:21:
In file included from hardware/ril-caf/libril/RilSocket.h:20:
hardware/ril-caf/libril/rilSocketQueue.h:19:10: fatal error: 'hardware/ril/librilutils/proto/sap-api.pb.h' file not found
#include <hardware/ril/librilutils/proto/sap-api.pb.h>